name: Deploy Frontend to Amazon EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  EC2_INSTANCE_IP: ${{ vars.EC2_INSTANCE_IP}}    # Replace with your EC2 instance IP
  BACKEND_URL: ${{ vars.BACKEND_URL }}  # Backend URL from secrets

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VITE_API_BASE_URL=${{ secrets.BACKEND_URL }}
          tags: |
            ghcr.io/geetpithadia3/finance-tracker-frontend:${{ github.sha }}
            ghcr.io/geetpithadia3/finance-tracker-frontend:main

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to GitHub Container Registry on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.EC2_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove existing container
            docker stop finance-tracker-frontend || true
            docker rm finance-tracker-frontend || true
            
            # Pull and run the new container on port 3000
            docker pull ghcr.io/geetpithadia3/finance-tracker-frontend:${{ github.sha }}
            
            docker run -d \
              --name finance-tracker-frontend \
              -p 3000:80 \
              --restart unless-stopped \
              ghcr.io/geetpithadia3/finance-tracker-frontend:${{ github.sha }}
            
            # Verify the container is running
            docker ps | grep finance-tracker-frontend
            
            # Reload nginx to ensure it picks up any changes
            sudo systemctl reload nginx